First review
arseniy96/bonus-program pull request #3
Opened 2023-07-16 16:42 UTC by arseniy96

2023-07-18 20:31 UTC, maxlyaptsev requested changes

2023-07-18 20:31 UTC, maxlyaptsev commented on internal/store/db.go
> +	// TODO: обернуть всё в транзакцию
обязательно) Еще хороший вариант сделать атомарное изменение баланса - т.е.
`UPDATE users SET bonuses=bonuses + $1`

2023-07-18 20:31 UTC, maxlyaptsev commented on internal/store/db.go
> +	amount := int(sum * 100)
а почему 100? Для перевода в миноры? Можно потерять т.к. кажется не понятным - можно либо комент оставить либо в отдельную функцию вынести convertTo

2023-07-18 20:31 UTC, maxlyaptsev commented on internal/server/authorization_handler.go
> +	jwt.RegisteredClaims
как правильно написал jwt используется просто чтобы убедиться что запрос не модифицировался. Его можно сделать в middleware и проверять все запросы. А для авторизации лучше использовать другое поле

2023-07-18 20:31 UTC, maxlyaptsev commented on internal/server/worker.go
> +	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
не очень понял логику работы с контекстом. Если есть таймаут в 3 секунды - нужно слушать завершение контекста - в том же select ниже. Если это таймаут только для запрса (куда контекст прокидывается ниже) то он тоже просрочится через 3 секунды, а дальше воркер будет крутиться с просроченным контекстом.

2023-07-18 20:31 UTC, maxlyaptsev commented on internal/server/worker.go
> +						ttl:   time.Now().Add(TTL),
я бы называл delay, ttl это time to live, не совсем то

2023-07-18 20:31 UTC, maxlyaptsev commented on internal/server/worker.go
> +				if res.Status == accrual.OrderStatusRegistered || res.Status == accrual.OrderStatusProcessing {
самодокументируемый код
```suggestion
				if hasFinalStatus(res) {
```

2023-07-18 20:31 UTC, maxlyaptsev commented on internal/server/worker.go
> +			s.OrdersQueue <- orderWithTTL
выполняем много лишней работы перекладывая обратно в канал. Скорость довольно большая, мы просто нагрузим процессор, он будет стараться изо всех сил т.к. даже если обрабатывать нечего - у всех стоит большой ttl - будем моенталльно вычитывать и класть следущую запись

вроде вариант интересный и кажется рабочим. Но много корнер-кейсов которые нарушают нормальную работу этого обработчика

2023-07-18 20:31 UTC, maxlyaptsev commented on internal/server/server.go
> +		OrdersQueue: make(chan OrderWithTTL, 1),
не слишком ли маленький капасити? Получается сможем работать только лишь с одним заказом. Если по заказу не будет своевременной информации по баллам, то просто заблокируемся при попытке записать второй заказ

2023-07-20 18:48 UTC, arseniy96 commented on internal/store/db.go
> +	// TODO: обернуть всё в транзакцию
А чё так можно было 😂

2023-07-20 18:48 UTC, arseniy96 commented on internal/store/db.go
> +	amount := int(sum * 100)
Вынесу в отдельную функцию 👍

2023-07-20 18:52 UTC, arseniy96 commented on internal/server/server.go
> +		OrdersQueue: make(chan OrderWithTTL, 1),
Да, это я для начала так написал, поставлю побольше)

2023-07-26 18:44 UTC, maxlyaptsev commented on internal/server/worker.go
> +package server
Хочется большего разбиение на пакеты - воркер другая сущность и не очень правильно что лежит вместе с моделями и ручками.

2023-07-26 18:44 UTC, maxlyaptsev approved these changes

2024-02-09 08:26 UTC, merged